"""add reading attempts

Revision ID: 33630ac8143f
Revises: 86a4df320dd0
Create Date: 2026-09-07 22:04:46.612509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33630ac8143f'
down_revision: Union[str, Sequence[str], None] = '86a4df320dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reading_test_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('band_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['reading_test_id'], ['reading_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_attempts_reading_test_id'), 'reading_attempts', ['reading_test_id'], unique=False)
    op.create_index(op.f('ix_reading_attempts_user_id'), 'reading_attempts', ['user_id'], unique=False)
    op.create_table('reading_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['reading_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_answers_attempt_id'), 'reading_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_reading_answers_question_id'), 'reading_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_answers_question_id'), table_name='reading_answers')
    op.drop_index(op.f('ix_reading_answers_attempt_id'), table_name='reading_answers')
    op.drop_table('reading_answers')
    op.drop_index(op.f('ix_reading_attempts_user_id'), table_name='reading_attempts')
    op.drop_index(op.f('ix_reading_attempts_reading_test_id'), table_name='reading_attempts')
    op.drop_table('reading_attempts')
    # ### end Alembic commands ###
